# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: |
          export CURRENT_DIR=`pwd`
          cd $CURRENT_DIR
          echo "CURRENT_DIR=$CURRENT_DIR" >> $GITHUB_ENV
          sudo apt install -y nodejs npm  && sudo pip install yq
          sudo npm install -g @angular/cli
      - name: Build
        run: |
          npm ci
          npm run build --production

      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: ${{ secrets.SFTP_PORT }}
            local_path: './static/*'
            remote_path: '~/SelecroApp/'
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
